### CREATE NEW STUDENT (SUCCESS)
POST http://localhost:3000/students
Content-Type: application/json

{
  "firstName": "Raymond",
  "lastName": "Mukonda",
  "studentNumber": "99",
  "email": "raymond.mukonda99@gmail.com",
  "age": 22,
  "course": "Software Engineering",
  "yearLevel": 3,
  "isRegistered": true
}

### DUPLICATE EMAIL (ERROR)
POST http://localhost:3000/students
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Tester",
  "studentNumber": "100",
  "email": "christ@gmail.com",
  "age": 20,
  "course": "Mathematics",
  "yearLevel": 2,
  "isRegistered": true
}

### DUPLICATE STUDENT NUMBER (ERROR)
POST http://localhost:3000/students
Content-Type: application/json

{
  "firstName": "Sarah",
  "lastName": "Duplicate",
  "studentNumber": "67",
  "email": "sarah.duplicate@gmail.com",
  "age": 21,
  "course": "Computer Science",
  "yearLevel": 3,
  "isRegistered": true
}

### GET ALL STUDENTS
GET http://localhost:3000/students


##CREATE NEW TEACHER (SUCCESS)
POST http://localhost:3000/teachers
Content-Type: application/json

{
  "firstName": "Daniel",
  "lastName": "Khumalo",
  "email": "daniel.khumalo@example.com",
  "department": "Computer Science"
}

##DUPLICATE EMAIL (ERROR)
POST http://localhost:3000/teachers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Duplicate",
  "email": "daniel.khumalo@example.com",
  "department": "Mathematics"
}

#get all teachers 
GET http://localhost:3000/teachers


###CREATE NEW COURSE (SUCCESS)
POST http://localhost:3000/courses
Content-Type: application/json

{
  "courseCode": "CS101",
  "courseName": "Introduction to Programming",
  "credits": 3,
  "department": "Computer Science"
}



###DUPLICATE COURSE CODE (ERROR)

POST http://localhost:3000/courses
Content-Type: application/json

{
  "courseCode": "CS101",
  "courseName": "Advanced Programming",
  "credits": 4,
  "department": "Software Engineering"
}


#### GET ALL COURSES
GET http://localhost:3000/courses
